name: CI
on: [push, workflow_dispatch]
jobs:
  CI:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.14.0
      - run: zig build test --summary all
      - run: zig build cov --summary all
      - run: zig build release --summary all
        if: runner.os == 'Linux'
      - run: find zig-out/ -type f -exec du -sh {} \;
        if: runner.os == 'Linux'
