name: CI
on: [push, workflow_dispatch]
jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mlugg/setup-zig@v1.2.1
        with:
          version: 0.14.0
      - run: zig build test
      - run: zig build --summary all
